{{ define "custom-node.rules.yaml.tpl" }}
groups:
- name: custom-node.rules
  rules:
  - alert: Kubernetes_One_Node_Lost_SLO
    expr: sum(kube_node_status_condition{condition="Ready",status="false"}) - sum(kube_node_spec_unschedulable) == 1
    for: 15s
    labels:
      severity: interrupt
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: node {{`{{$labels.instance}}`}} is failing
      summary: Kubernetes detected 1 node with availability issue for at least 15s
      grafana: d/zn2oeyZiz/network-checker?
  - alert: Kubernetes_Two_Nodes_Lost_SLO
    expr: sum(kube_node_status_condition{condition="Ready",status="false"}) - sum(kube_node_spec_unschedulable) == 2
    for: 5m
    labels:
      severity: page
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: Kubernetes detects that 2 or more nodes are failing for more than 5m
      summary: Node availability for 5m
      grafana: d/zn2oeyZiz/network-checker?
  - alert: Kubernetes_Nodes_Availability_SLA_Page
    expr: sum(kube_node_status_condition{condition="Ready",status="false"}) - sum(kube_node_spec_unschedulable) >= 3
    for: 5m
    labels:
      severity: page
      serviceLevel: agreement
      type: functional
    annotations:
      description: Kubernetes detects that 3 or more nodes are failing for more than 5m
      summary: Node availability for 5m
      grafana: d/zn2oeyZiz/network-checker?
  - alert: Nodes_Disk_Space_Used_Warning
    expr: ((node_filesystem_size_bytes{mountpoint="/rootfs/mnt/data"} - node_filesystem_free_bytes{mountpoint="/rootfs/mnt/data"}) / node_filesystem_size_bytes{mountpoint="/rootfs/mnt/data"}) * 100 > 65
    for: 15m
    labels:
      severity: interrupt
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: Node filesystem used > 65%
      summary: Node filesystem used > 65%
      grafana: d/pPJ4QFGik/server-metrology?
  - alert: Nodes_Disk_Space_Used_Critical
    expr: ((node_filesystem_size_bytes{mountpoint="/rootfs/mnt/data"} - node_filesystem_free_bytes{mountpoint="/rootfs/mnt/data"}) / node_filesystem_size_bytes{mountpoint="/rootfs/mnt/data"}) * 100 > 85
    for: 5m
    labels:
      severity: page
      serviceLevel: objective
      team: infra
      type: functional
    annotations:
      description: Node filesystem used > 85%
      summary: Node filesystem used > 85%
      grafana: d/pPJ4QFGik/server-metrology?
{{ end }}