apiVersion: v1
kind: Service
metadata:
  name: {{ template "exporter-node.name" . }}
  labels:
    app: {{ template "exporter-node.name" . }}
    component: node-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.externalPort }}
    targetPort: metrics
    protocol: TCP
  selector:
    app: {{ template "exporter-node.name" . }}
    component: node-exporter
    release: {{ .Release.Name }}
