# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: quay.io/prometheus/node-exporter
  tag: v0.15.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 9100
  containerPort: 9100

resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi

container:
  args:
  - --path.procfs=/host/proc
  - --path.sysfs=/host/sys
  - --collector.filesystem.ignored-mount-points
  - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs|rootfs/opt/docker/devicemapper)($$|/)"

  volumes:
  - name: proc
    hostPath:
      path: /proc
  - name: sys
    hostPath:
      path: /sys
  - name: rootfs
    hostPath:
      path: /

  volumeMounts:
  - name: proc
    mountPath: /host/proc
    readOnly:  true
  - name: sys
    mountPath: /host/sys
    readOnly: true
  - name: rootfs
    mountPath: /rootfs
    readOnly: true
 
## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
- effect: NoSchedule
  operator: Exists


# default rules are in templates/node.rules.yaml
# prometheusRules: {}
